### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by vivekvardhanadepu** [vivekvardhanadepu/user-friendly-lexical-training#2]
- [ ] non-parallel corpora training 
- [ ] why only target words in biltrans output?
- [ ] multitrans vs process-tagger-output
- [ ] fast-align --> random??
- [ ] 2>ngrams >ngrams alternative
- [ ] first sl tag != first tl tag
- [ ] apertium stream parser
- [ ] inf, nan in rules
- [ ] overwrite folder/files already present prompt
- [ ] Top N rules
- [ ] collapsing rules
- [ ] finding non-parallel corpora[if possible, extraction of parallel sentences from them]
